[package]
name = "hbx-retention"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hbx-core = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
