[package]
name = "hbx-badou-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hbx-core = { workspace = true }
badou-hbop-client = { workspace = true }
badou-proto = { workspace = true }
tonic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
blake3 = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }
prost-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }