[package]
name = "hbx-crypto-password"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hbx-core = { workspace = true }
argon2 = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
